/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pp.designv2;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import pp.negocio.*;

/**
 *
 * @author Utilizador
 */
public class JanelaAdicionarCliente extends javax.swing.JFrame {
    private Sistema sistema;
    private Proprietario cliente;
    private ListarClientes jc;
   
    public JanelaAdicionarCliente(Sistema sistema, Proprietario cliente, ListarClientes jc) {
        initComponents();
        setSize(391, 438);
        this.jc = jc;
        this.sistema = sistema;
        this.cliente = cliente;
        
        
        if (registoNovo()) {    
            //Altera o titulo da janela
            //Como construimos sempre uma nova janela, as caixas de texto já estão limpas
            setTitle("Criação de novo cliente");
            nameField.requestFocus();                      
        }else{
            //No caso de um registo existente
            //Altera o titulo da janela
            setTitle("Alteração de dados de cliente");
            //Preenche as caixas de texto com os dados do utilizador
            nameField.setText(cliente.getNome());
            nifField.setText(String.valueOf(cliente.getNif()));
            moradaField.setText(cliente.getMorada());
            telefoneField.setText(String.valueOf(cliente.getTelefone()));
            mailField.setText(cliente.getMail());
            //txtPassword.requestFocus();
        }   
        this.setResizable(false);
    }
    
     private boolean registoNovo() {
        //Se utililizador == null consideramos que é um novo registo
        return cliente == null;
    }   
    
    private void fechar() {
        dispose();
    }
    
    private void criarCliente(){
        
        if (registoNovo() && nameField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o nome!");            
            nameField.requestFocus();
            return;
        }
        
        if (registoNovo() && nifField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o NIF!");            
            nifField.requestFocus();
            return;
        }
        
        if (registoNovo() && telefoneField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o contacto!");            
            telefoneField.requestFocus();
            return;
        } 
        
        
        if (registoNovo() && moradaField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a moradas!");            
            moradaField.requestFocus();
            return;
        } 
        
        
        if (registoNovo() && mailField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o e-mail!");            
            mailField.requestFocus();
            return;
        } 
        
        
        if(sistema.getListaProp().containsKey(nifField.getText())){
            
            JOptionPane.showMessageDialog(this, "O NIF pretendido já está em uso");
                return;
        }
        
        if(registoNovo()){ 
            nameField.setEditable(true);
            Proprietario xpto = new Proprietario();
            xpto.setMail(mailField.getText());
            xpto.setMorada(moradaField.getText());
            xpto.setNif(Integer.parseInt(nifField.getText()));
            xpto.setNome(nameField.getText());
            xpto.setTelefone(Integer.parseInt(telefoneField.getText()));
       
        try {
                sistema.adicionar(xpto);
           } catch (Sistema.ClienteDuplicadoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }  
       
       }
       else{
           cliente.setNome(nameField.getText());
           cliente.setNif(Integer.parseInt(nifField.getText()));
           cliente.setMorada(moradaField.getText());
           cliente.setMail(mailField.getText());
           cliente.setTelefone(Integer.parseInt(telefoneField.getText()));
                 
        }
        
        
        if (jc != null) jc.atualizar();  
        
        JOptionPane.showMessageDialog(this, "Registo guardado com sucesso.");
        fechar();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nifField = new javax.swing.JTextField();
        telefoneField = new javax.swing.JTextField();
        moradaField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 29, 110, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 75, 100, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 118, 110, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Morada:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 164, 100, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 210, 80, 14);
        getContentPane().add(nameField);
        nameField.setBounds(156, 26, 180, 20);
        getContentPane().add(nifField);
        nifField.setBounds(156, 72, 180, 20);
        getContentPane().add(telefoneField);
        telefoneField.setBounds(156, 118, 180, 20);
        getContentPane().add(moradaField);
        moradaField.setBounds(156, 164, 180, 20);
        getContentPane().add(mailField);
        mailField.setBounds(156, 210, 180, 20);

        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/accept.png"))); // NOI18N
        okBtn.setText("Confimar");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        getContentPane().add(okBtn);
        okBtn.setBounds(40, 330, 120, 38);

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/cancel.png"))); // NOI18N
        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(210, 330, 120, 36);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/nossa_emrpesa.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, -40, 420, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        fechar();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        criarCliente();
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField moradaField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nifField;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField telefoneField;
    // End of variables declaration//GEN-END:variables
}
