/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pp.designv2;

import pp.negocio.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author André
 */
public class JanelaOrcamento extends javax.swing.JFrame {

    private Sistema sistema;
    private Fracao fracao;
    private ListarFracoes lf;
    private Condominio condo;
    /**
     * Creates new form JanelaOrcamento
     */
    public JanelaOrcamento() {
        initComponents();
        setSize(403, 443);
        this.setResizable(false);
    }
    
    private boolean registoNovo() {
        //Se utililizador == null consideramos que é um novo registo
        return fracao == null;
    }   
    
    private void fechar() {
        dispose();
    }
    
    public void calcularOrcamento(){
        double total = 0;
        
        if (registoNovo() && luzField.getText().isEmpty() || Integer.parseInt(luzField.getText()) < 0  ) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de despesa da luz!");            
            luzField.requestFocus();
            return;
        }
        
        if (registoNovo() && aguaField.getText().isEmpty() || Integer.parseInt(aguaField.getText()) < 0 ) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de despesa da água!");            
            aguaField.requestFocus();
            return;
        }
        
        if (registoNovo() && telefoneField.getText().isEmpty() || Integer.parseInt(telefoneField.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de despesa do telefone!");            
            telefoneField.requestFocus();
            return;
        }
        
        if (registoNovo() && elevadorField.getText().isEmpty() || Integer.parseInt(elevadorField.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de despesa do elevador!");            
            elevadorField.requestFocus();
            return;
        }
        
        if (registoNovo() && limpezaField.getText().isEmpty() || Integer.parseInt(limpezaField.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de despesa da limpeza!");            
            limpezaField.requestFocus();
            return;
        }
        
        if (registoNovo() && manutencaoField.getText().isEmpty() || Integer.parseInt(manutencaoField.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de despesa da manutenção geral!");            
            manutencaoField.requestFocus();
            return;
        }
        
        if (registoNovo() && fundoField.getText().isEmpty() || Integer.parseInt(fundoField.getText()) < 0 || Integer.parseInt(fundoField.getText()) > 100) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. um valor válido de fundo de reserva obrigatório!");            
            fundoField.requestFocus();
            return;
        }
        
        int luz = Integer.parseInt(luzField.getText());
        int agua = Integer.parseInt(aguaField.getText());
        int telefone = Integer.parseInt(telefoneField.getText());
        int elevador = Integer.parseInt(elevadorField.getText());
        int limpeza = Integer.parseInt(limpezaField.getText());
        int manutencao = Integer.parseInt(manutencaoField.getText());
        double fundo = Integer.parseInt(fundoField.getText());
        fundo = (fundo / 100);
        
        total = (luz + agua + telefone + elevador + limpeza + manutencao);
        total = (int) total + (total * fundo);
        
        
        String anual =  Double.toString(total);
        
        resultadoAnualLabel.setText(anual);
        
        total = (total / 12);
        
        String mensal = Double.toString(total);
        
        resultadoMensalLabel.setText(mensal);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        luzField = new javax.swing.JTextField();
        aguaField = new javax.swing.JTextField();
        telefoneField = new javax.swing.JTextField();
        elevadorField = new javax.swing.JTextField();
        limpezaField = new javax.swing.JTextField();
        manutencaoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fundoField = new javax.swing.JTextField();
        resultadoAnualLabel = new javax.swing.JLabel();
        resultadoMensalLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(luzField);
        luzField.setBounds(220, 12, 90, 20);
        getContentPane().add(aguaField);
        aguaField.setBounds(220, 49, 90, 20);
        getContentPane().add(telefoneField);
        telefoneField.setBounds(220, 80, 90, 20);
        getContentPane().add(elevadorField);
        elevadorField.setBounds(220, 114, 90, 20);
        getContentPane().add(limpezaField);
        limpezaField.setBounds(220, 152, 90, 20);
        getContentPane().add(manutencaoField);
        manutencaoField.setBounds(220, 189, 90, 20);

        jLabel1.setText("Luz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 110, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Água");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 100, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 110, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Elevador");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 130, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Limpeza");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 120, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manutenção Geral");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 190, 130, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/calculator.png"))); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(65, 354, 120, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fundo de reserva obrigatório");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(52, 230, 180, 14);
        getContentPane().add(fundoField);
        fundoField.setBounds(220, 230, 90, 20);
        getContentPane().add(resultadoAnualLabel);
        resultadoAnualLabel.setBounds(220, 271, 150, 12);
        getContentPane().add(resultadoMensalLabel);
        resultadoMensalLabel.setBounds(220, 301, 160, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Orçamento Anual");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 270, 190, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Orçamento Mensal");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 300, 190, 14);

        sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/cancel.png"))); // NOI18N
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(216, 354, 100, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/nossa_emrpesa.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularOrcamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        fechar();
    }//GEN-LAST:event_sairButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aguaField;
    private javax.swing.JTextField elevadorField;
    private javax.swing.JTextField fundoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField limpezaField;
    private javax.swing.JTextField luzField;
    private javax.swing.JTextField manutencaoField;
    private javax.swing.JLabel resultadoAnualLabel;
    private javax.swing.JLabel resultadoMensalLabel;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField telefoneField;
    // End of variables declaration//GEN-END:variables
}
