/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pp.designv2;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import pp.negocio.Administrador;
import pp.negocio.*;
import java.awt.BorderLayout;
import java.awt.GridLayout;
/**
 *
 * @author Utilizador
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    private Sistema sistema;
    //private Condominus dados;
    //private Condominus app;
  
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal(Sistema sistema) {
        initComponents();
        setSize(1171, 815);
        this.sistema = sistema;
        this.setResizable(false);
        
        //Força a maximização da janela
        //this.setExtendedState(JanelaPrincipal.MAXIMIZED_BOTH);    
        
        //O processo de fecho da janela será controlado pelo programa
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        //Apenas mostra o menu de administração se o utilizador for um administrador
        mnuAdministrador.setVisible(sistema.getUtilizadorLigado() instanceof Administrador);
        
        //Apenas mostra o menu de utilizador se o de administração estiver oculto
       // mnuUtilizador.setVisible(!mnuAdministrador.isVisible()); 
       
       //this.dados = dados;
        setResizable(true);
        setLocationRelativeTo(null);
        //add(backGround);
        //BorderLayout teste = new BorderLayout();
        //backGround.setBorder(teste);
        
       
    }
  
    
    private void alterarPassword() {
        JanelaAlteracaoDadosUtilizador psw = new JanelaAlteracaoDadosUtilizador(sistema);
        psw.setVisible(true);
    }
    
    
    private void mostraClientes() {
        ListarClientes psw = new ListarClientes(sistema);
        psw.setVisible(true);
        psw.setTitle("Lista de Clientes");
    }
    
    public void mostrarCondominios(){
        ListarCondominios cond = new ListarCondominios(sistema);
        cond.setVisible(true);
        cond.setTitle("Lista de Condominios");
    }
    
    private void terminar() {        
        if (JOptionPane.showConfirmDialog(null, 
                "Deseja realmente terminar o programa?", 
                "Terminar", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            sistema.terminar();
        }
  
    }
    
    private void mostrarRecibos(){
        ListarRecibos ref = new ListarRecibos(sistema);
        ref.setVisible(true);
        ref.setTitle("Facturas e Recibos");
    }
    
    private void mostrarEventos(){
        ListarEventos ref = new ListarEventos(sistema);
        ref.setVisible(true);
        ref.setTitle("Eventos");
    }

    
    private void consultaEstatistica(){
        JanelaEstatistica window = new JanelaEstatistica(sistema);
        window.setVisible(true);
        window.setTitle("Informações sobre a Empresa");
        
    }
    
    public void regulamento(){
            
            //Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler" + "C:\\Users\\André\\Dropbox\\ProjetoGrupo\\CodigoCivil.pdf");
        
        try {
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                desktop.open(new File("C:\\Users\\André\\Dropbox\\ProjetoGrupo\\CodigoCivil.pdf"));
            } else {
                System.out.println("Open is not supported");
            }
        } catch (IOException exp) {
            JOptionPane.showMessageDialog(null, exp);
        }
            
    }
    
    private void consultarOrcamento(){
        JanelaOrcamento jo = new JanelaOrcamento();
        jo.setVisible(true);
        jo.setTitle("Novo orçamento");
    }
    
    
    public void consultarSobre(){
        JanelaSobre js = new JanelaSobre();
        js.setVisible(true);
        js.setTitle("Sobre o Software");
    }
    
    public void consultarRegulamento(){
        JanelaRegulamento jr = new JanelaRegulamento();
        jr.setVisible(true);
        jr.setTitle("Regulamento do Condominio");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        condominiosBtn = new javax.swing.JButton();
        clientesBtn = new javax.swing.JButton();
        recibosBtn = new javax.swing.JButton();
        statBtn = new javax.swing.JButton();
        orcamentoButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGeral = new javax.swing.JMenu();
        menuGTerminar = new javax.swing.JMenuItem();
        mnuAdministrador = new javax.swing.JMenu();
        menuUserPw = new javax.swing.JMenuItem();
        regulamentoMenu = new javax.swing.JMenu();
        regulamentoField = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenuItem3.setText("jMenuItem3");
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        jPopupMenu1.add(jMenuItem5);

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONDOMINUS");
        setBackground(new java.awt.Color(181, 201, 236));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1171, 815));
        setMinimumSize(new java.awt.Dimension(1171, 815));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        condominiosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/Condomino.png"))); // NOI18N
        condominiosBtn.setBorder(null);
        condominiosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condominiosBtnActionPerformed(evt);
            }
        });
        getContentPane().add(condominiosBtn);
        condominiosBtn.setBounds(20, 20, 150, 120);

        clientesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/welele_1.jpg"))); // NOI18N
        clientesBtn.setBorder(null);
        clientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clientesBtn);
        clientesBtn.setBounds(50, 610, 160, 170);

        recibosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/tipo_recibo.jpg"))); // NOI18N
        recibosBtn.setBorder(null);
        recibosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibosBtnActionPerformed(evt);
            }
        });
        getContentPane().add(recibosBtn);
        recibosBtn.setBounds(1020, 20, 150, 130);

        statBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/estatistica.jpg"))); // NOI18N
        statBtn.setText("Estatística");
        statBtn.setBorder(null);
        statBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statBtnActionPerformed(evt);
            }
        });
        getContentPane().add(statBtn);
        statBtn.setBounds(1020, 620, 140, 130);

        orcamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/orçamento.jpg"))); // NOI18N
        orcamentoButton.setBorder(null);
        orcamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamentoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(orcamentoButton);
        orcamentoButton.setBounds(550, 270, 150, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/eventosicon3.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 20, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/Fundo v5.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1430, 960);

        menuGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/application.png"))); // NOI18N
        menuGeral.setText("Geral");

        menuGTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/door_out.png"))); // NOI18N
        menuGTerminar.setText("Terminar");
        menuGTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGTerminarActionPerformed(evt);
            }
        });
        menuGeral.add(menuGTerminar);

        jMenuBar1.add(menuGeral);

        mnuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/user_suit.png"))); // NOI18N
        mnuAdministrador.setText("Utilizador");

        menuUserPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/user_edit.png"))); // NOI18N
        menuUserPw.setText("Alterar informações");
        menuUserPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserPwActionPerformed(evt);
            }
        });
        mnuAdministrador.add(menuUserPw);

        jMenuBar1.add(mnuAdministrador);

        regulamentoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/information.png"))); // NOI18N
        regulamentoMenu.setText("Sobre");
        regulamentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulamentoMenuActionPerformed(evt);
            }
        });

        regulamentoField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/book.png"))); // NOI18N
        regulamentoField.setText("Regulamento");
        regulamentoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulamentoFieldActionPerformed(evt);
            }
        });
        regulamentoMenu.add(regulamentoField);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/exclamation.png"))); // NOI18N
        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        regulamentoMenu.add(jMenuItem2);

        jMenuBar1.add(regulamentoMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGTerminarActionPerformed
        terminar();
    }//GEN-LAST:event_menuGTerminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        terminar();
    }//GEN-LAST:event_formWindowClosing

    private void menuUserPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserPwActionPerformed
        alterarPassword();
    }//GEN-LAST:event_menuUserPwActionPerformed

    private void condominiosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condominiosBtnActionPerformed
        mostrarCondominios();
    }//GEN-LAST:event_condominiosBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);  
       

    }//GEN-LAST:event_formWindowOpened

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
        if(evt.isPopupTrigger()){
                jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void recibosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibosBtnActionPerformed
        mostrarRecibos();  
     
    }//GEN-LAST:event_recibosBtnActionPerformed

    private void regulamentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulamentoMenuActionPerformed
        regulamento();
    }//GEN-LAST:event_regulamentoMenuActionPerformed

    private void statBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statBtnActionPerformed
        consultaEstatistica();  // TODO add your handling code here:
    }//GEN-LAST:event_statBtnActionPerformed

    private void orcamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamentoButtonActionPerformed
        consultarOrcamento();
    }//GEN-LAST:event_orcamentoButtonActionPerformed

    private void clientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBtnActionPerformed
        mostraClientes();// TODO add your handling code here:
    }//GEN-LAST:event_clientesBtnActionPerformed

    private void regulamentoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulamentoFieldActionPerformed
        consultarRegulamento();
    }//GEN-LAST:event_regulamentoFieldActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        consultarSobre();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mostrarEventos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientesBtn;
    private javax.swing.JButton condominiosBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem menuGTerminar;
    private javax.swing.JMenu menuGeral;
    private javax.swing.JMenuItem menuUserPw;
    private javax.swing.JMenu mnuAdministrador;
    private javax.swing.JButton orcamentoButton;
    private javax.swing.JButton recibosBtn;
    private javax.swing.JMenuItem regulamentoField;
    private javax.swing.JMenu regulamentoMenu;
    private javax.swing.JButton statBtn;
    // End of variables declaration//GEN-END:variables

//método para a hora
    
   /* class Hora implements ActionListener{
       public void actionPerformad(ActionEvent e){
            Calendar now = Calendar.getInstance();
            jlhora.setText(String.format("1$tH:%1$tM:%1$tS", now)); 
        }}
*/
}
