/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pp.designv2;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author André
 */
public class JanelaSobre extends javax.swing.JFrame {

    /**
     * Creates new form JanelaSobre
     */
    public JanelaSobre() {
        initComponents();
        setSize(532, 435);
        sobreText.setEditable(false);
        sobreText.setText("Product Version: Condominus 1.0 (Build 201510222201)" + "\n");
        sobreText.setText(sobreText.getText() + "Updates: Condominus is updated to version Condominus 1.0 Patch 1" + "\n");
        sobreText.setText(sobreText.getText() + "System: Windows 10 version 10.0 running on amd64; Cp1252; pt_PT (nb)" + "\n");
        sobreText.setText(sobreText.getText() + "Paradigmas da Programação 2015/2016" + "\n");
        sobreText.setText(sobreText.getText() + "Made by: Fantastic 4" + "\n");
        this.setResizable(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sobreText = new javax.swing.JTextPane();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/logo v2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 11, 469, 125);

        jScrollPane1.setViewportView(sobreText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(31, 202, 469, 110);

        sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/cancel.png"))); // NOI18N
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(185, 330, 159, 36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextPane sobreText;
    // End of variables declaration//GEN-END:variables
}
