/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pp.designv2;

import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import pp.negocio.*;
/**
 *
 * @author Utilizador
 */
public class ListarEventos extends javax.swing.JFrame {
    private Sistema sistema;
    private AbstractTableModel modeloTabela;
    /**
     * Creates new form ListarEventos
     */
    public ListarEventos(Sistema sistema) {
        initComponents();
        setSize(968, 662);
        this.sistema = sistema;
        this.modeloTabela = criarModelo();
        eventosTable.setModel(modeloTabela);
        this.setResizable(false);
    }
    
    
   
    private AbstractTableModel criarModelo() {   
        String[] nomeColunas = {"Tipo de Evento", "Data", "Equipa", "Notas"};
        
        return new AbstractTableModel() {     
            @Override
            public String getColumnName(int column) {
                return nomeColunas[column];
            }
           
            @Override
            public int getRowCount() {
                //Retorna o número de linhas que a tabela deverá ter
                return sistema.getListaEventos().size();
            }

            @Override
            public int getColumnCount() {
                //Retorna o número de colunas que a tabela deverá ter
                return nomeColunas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
           
            
                switch (columnIndex) {
                    case 0: 
                        return sistema.getListaEventos().get(rowIndex).getTipo();
                    case 1:
                        return sistema.getListaEventos().get(rowIndex).getData();
                    case 2:
                        return sistema.getListaEventos().get(rowIndex).getStaff();
                    case 3:
                        return sistema.getListaEventos().get(rowIndex).getNotas();
                    default:
                        return "";
                }                              
            }            
        };
    }
    
    public void atualizar() {    
        //Informa o modelo que foram efetuadas alteracoes, o modelo informa a tabela e os dados são redesenhados
        modeloTabela.fireTableDataChanged();
    }
    
    
    public void fechar(){
        dispose();
        
    }
    
    public void novoEvento(){
        JanelaAdicionarEvento ref = new JanelaAdicionarEvento(sistema, null, null, null, this);
        ref.setVisible(true);
    }
    
    public void removerEvento(){
        int rowIndex = eventosTable.getSelectedRow();
        if (rowIndex == -1) { JOptionPane.showMessageDialog(this, "Nenhum evento selecionado"); return;}
        //int ref =  Integer.parseInt(modeloTabela.getValueAt(rowIndex, 0));
        sistema.getListaEventos().remove(rowIndex);
        modeloTabela.fireTableDataChanged();
    }
    
    public void editarEvento(){
        int rowIndex = eventosTable.getSelectedRow();
        if (rowIndex == -1) { JOptionPane.showMessageDialog(this, "Nenhum evento selecionado"); return;}
        //int ref =  Integer.parseInt(modeloTabela.getValueAt(rowIndex, 0));
        EventoData2 edit = sistema.getListaEventos().get(rowIndex);
        JanelaAdicionarEvento ref = new JanelaAdicionarEvento(sistema, null, edit, null,  this);
        ref.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        eventosTable = new javax.swing.JTable();
        newBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        eventosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(eventosTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(37, 35, 894, 252);

        newBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/calendar_add.png"))); // NOI18N
        newBtn.setText("Novo Evento");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newBtn);
        newBtn.setBounds(37, 523, 140, 39);

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/calendar_edit.png"))); // NOI18N
        editBtn.setText("Editar Evento");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn);
        editBtn.setBounds(299, 523, 140, 39);

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/calendar_delete.png"))); // NOI18N
        delBtn.setText("Remover Evento");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBtn);
        delBtn.setBounds(553, 523, 160, 39);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/cancel.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(826, 523, 105, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp/designbonus/imagem fundo v10.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        novoEvento();        // TODO add your handling code here:
    }//GEN-LAST:event_newBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        editarEvento();        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        removerEvento();        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTable eventosTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBtn;
    // End of variables declaration//GEN-END:variables
}
